### ISSUE TITLE
Placeholders not being replaced in policies

### ISSUE THREAD

**Issue by albertored11** [cloudera-labs/terraform-cdp-modules#18]
In `aws_iam_policy.cdp_datalake_backup_policy` and `aws_iam_policy.cdp_datalake_restore_policy` resources, placeholders are not being replaced.

In the case of the first one, [the template](https://raw.githubusercontent.com/hortonworks/cloudbreak/master/cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-backup-policy.json) it is using for the policy contains the `${BACKUP_LOCATION_BASE}` placeholder, but it is not replaced in the Terraform module.

From the code in [defaults.tf](https://github.com/cloudera-labs/terraform-cdp-modules/blob/main/modules/terraform-cdp-aws-pre-reqs/defaults.tf#L159), I assume it is trying to replace `<BACKUP_LOCATION_BASE>` instead of `${BACKUP_LOCATION_BASE}`.

In the case of the second one, the same happens with its respective [template](https://raw.githubusercontent.com/hortonworks/cloudbreak/master/cloud-aws-cloudformation/src/main/resources/definitions/aws-datalake-restore-policy.json).

From the code in [defaults.tf](https://github.com/cloudera-labs/terraform-cdp-modules/blob/main/modules/terraform-cdp-aws-pre-reqs/defaults.tf#L172), I assume it is trying to replace `<your-backup-bucket>` instead of `${BACKUP_LOCATION_BASE}`.

This results in a faulty plan:

![image](https://github.com/cloudera-labs/terraform-cdp-modules/assets/38332200/a273a3d4-403e-43e3-8bcb-4dbbc3372303)

![image](https://github.com/cloudera-labs/terraform-cdp-modules/assets/38332200/ee2d8773-37e1-42b2-a6c4-c9419d84abcc)

**Comment by jimright** [comment]
Hi @albertored11,

Good spot, there's been a change to the placeholders in the last number of days.
I will patch the code and let you know when a fix is available.

Thanks for raising the issue.
