### ISSUE TITLE
Cant change datalake image to CentOS 7 

### ISSUE THREAD

**Issue by hndordix** [cloudera-labs/terraform-cdp-modules#67]
I am currently automating the creation of a Cloudera CDP environment with Azure as the cloud provider. I have to use CentOS7 as the operating system. To change the operating system and the corresponding image of the data lake, I would use the ‘datalake_image’ variable of the cdp-deploy module. However, to be able to use this, ‘datalake_version’ must be set to null. When compiling, I always get the error that ‘datalake_version’ must not be null. How else can I change the image of the datalake? 

Error message:  
│ Error: Invalid function argument
│
│   on modules\terraform-cdp-deploy\variables.tf line 226, in variable "datalake_version":
│  226:     condition     = (var.datalake_version == "latest" ? true : length(regexall("\\d+\\.\\d+.\\d+", var.datalake_version)) > 0)
│     ├────────────────
│     │ while calling regexall(pattern, string)
│     │ var.datalake_version is null
│
│ Invalid value for "string" parameter: argument must not be null.

**Comment by jimright** [comment]
Hi @hndordix,

As part of PR #68, we've updated the validation on the `datalake_version` input variable to allow `null`.
We have also created a 0.7.1 release tag for this version of the modules.

When you get a chance can you test if this resolves your issues?
I suspect you may also need the changes in PR #57 as this allows the major OS version to be specified. We hit some issues when testing this which might require an update on the CDP provider.
